/** Aggregated tool metrics from evolution API. */
export interface ToolAggregate {
  tool_name: string;
  call_count: number;
  success_rate: number;
  avg_duration_ms: number;
}

/** Aggregated retrieval metrics from evolution API. */
export interface RetrievalAggregate {
  source: string;
  query_count: number;
  usage_rate: number;
  avg_score: number;
}

/** Aggregated skill quality score from calls, feedback, and regression signals. */
export interface SkillQualityScore {
  skill_name: string;
  call_count: number;
  success_rate: number;
  avg_duration_ms: number;
  feedback_corrections: number;
  regression_failures: number;
  quality_score: number;
  risk_level: "low" | "medium" | "high";
}

/** Evolution suggestion generated by the suggestion engine. */
export interface EvolutionSuggestion {
  id: string;
  agent_id: string;
  suggestion_type: "threshold" | "tool_order" | "skill_add" | "feedback_correction" | "skill_repair";
  suggestion: string;
  rationale: string;
  parameters: Record<string, unknown> | null;
  status: "pending" | "approved" | "rejected" | "applied" | "rolled_back";
  reviewed_by: string | null;
  reviewed_at: string | null;
  created_at: string;
}

/** Aggregated metrics response from GET /evolution/metrics?aggregate=true. */
export interface AggregatedMetrics {
  tool_aggregates: ToolAggregate[];
  retrieval_aggregates: RetrievalAggregate[];
  skill_quality_scores: SkillQualityScore[];
}

export interface EvolutionFeedbackValue {
  feedback_type: "useful" | "not_useful" | "correction";
  message_ref: string;
  message_content?: string;
  correction?: string;
  user_id?: string;
  requires_approval: boolean;
  status: string;
}

export interface EvolutionFeedback {
  id: string;
  tenant_id: string;
  agent_id: string;
  session_key: string;
  metric_type: "feedback";
  metric_key: string;
  value: EvolutionFeedbackValue;
  created_at: string;
}

export interface CreateEvolutionFeedbackInput {
  feedback_type: "useful" | "not_useful" | "correction";
  session_key: string;
  message_ref: string;
  message_content?: string;
  correction?: string;
}

export interface EvolutionRegressionCase {
  name: string;
  status: "passed" | "failed" | "skipped";
  message: string;
}

export interface EvolutionRegressionRun {
  run_id: string;
  status: "passed" | "failed" | "skipped";
  scope: string;
  suggestion_id?: string;
  total: number;
  passed: number;
  failed: number;
  started_at: string;
  completed_at: string;
  cases: EvolutionRegressionCase[];
}

export interface EvolutionAuditEvent {
  action: string;
  actor?: string;
  suggestion_id?: string;
  status?: string;
  result: "ok" | "failed" | string;
  message?: string;
  created_at: string;
}

/** Adaptation guardrails stored in agent other_config. */
export interface AdaptationGuardrails {
  max_delta_per_cycle: number;
  min_data_points: number;
  rollback_on_drop_pct: number;
  locked_params: string[];
}
